metrics:
    markdown_custom:
        label: Markdown
        layer: ~
        timeline: true

    markdown_to_html:
        label: 'Markdown to HTML'
        layer: markdown_custom
        timeline: true
        matching_calls:
            php:
                -
                    callee: "=App\\Utils\\Markdown::toHtml"
                    contrib: count-only

    greetings:
        label: Greetings phrases
        matching_calls:
            php:
                -
                    callee:
                        selector: "=App\\Utils\\Greetings::phrase"
                        argument:
                            1: "/^(Hello|Hi)/"
                            2: "*"

tests:
    'All pages are fast':
        path: '/.*'
        assertions:
            - 'main.wall_time < 200ms'
            - 'main.memory < 10Mb'

    'Twig displays and renders':
        path: '/.*'
        assertions:
            - 'metrics.twig.display.count + metrics.twig.render.count < 40'

    'Symfony events dispatched':
        path: '/.*'
        assertions:
            - 'metrics.symfony.events.count < 25'

    'Not too many SQL queries on the homepage':
        path: '/(en|fr)/blog/'
        assertions:
            - 'metrics.sql.queries.count < 5'

    'No external HTTP requests on the homepage':
        path: '/(en|fr)/blog/'
        assertions:
            - 'metrics.http.requests.count == 0'

    'Test':
        path: '/.*'
        assertions:
            - "percent(main.wall_time) < 10%"

