version: 2.1
description: Foo1

orbs:
    blackfire: blackfireio/php@1.1
    blackfire-agent: blackfireio/agent@1.2
    blackfire-player: blackfireio/player@1.0

    symfony:
        commands:
            install:
                steps:
                    - run:
                          name: Install Symfony CLI
                          command: |
                              wget https://get.symfony.com/cli/installer -O - | sudo bash -s -- --install-dir=/usr/local/bin
                              mkdir ~/.ssh
                              echo "*.eu.s5y.io ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCrpeug3uW2t83g2HU40FBsuT1mD+7K6JZY6ayVb/634PNlWa4LtFgUnmv8lXuX6+3aFHXFI+l0OcbUYAe1nN0FTeEfJAVrbWJWC0CATUrMGw8UqU8zpTaVIpLn+nv/kYtRLoJ0EiCcldJh4AIsos2hWqqne/Jo/+jiBiUnQvkcc+hW92hzxs/QWu78TvKKk3zjOFgktHuRThmMYWoFtR2oZLJHVXcH9lrLxRMO1kNCIb4aOeErOI1PXi6lGqlefA8qUlj+vrFlQAobI4yKuUF8a9+IrK2l9UN4eUjhl4MnRmW7YmrxjD7vxhwu7pLtgyvIXf+oYm4chvlEcqFJeEND" >> ${HOME}/.ssh/known_hosts

                              symfony version

            deploy:
                parameters:
                    project-id:
                        type: string

                steps:
                    - run:
                          name: Symfony deploy
                          command: |
                              symfony link <<parameters.project-id>>
                              symfony deploy

            local_server_run:
                steps:
                    - run:
                          name: Run Symfony server
                          environment:
                              APP_DEBUG: 0
                          command: symfony local:server:start -d

references:
    default_executor: &default_executor
        docker:
            - image: circleci/php:7.4-fpm-node

    apcu_install: &apcu_install
        run:
            name: Install APCu
            command: sudo pecl install apcu && sudo docker-php-ext-enable apcu

    symfony_server_start: &symfony_server_start
        run:
            name: "Install & run Symfony server"
            environment:
                APP_ENV: prod
            command: |
                wget https://get.symfony.com/cli/installer -O - | bash
                ~/.symfony/bin/symfony local:server:start -d
                php bin/console cache:warmup -e prod

jobs:
    build:
        <<: *default_executor

        steps:
            - checkout

            - *apcu_install
            - run:
                  name: Install SOAP
                  command: |
                      # SOAP (for PaylineBundle)
                      sudo apt update && sudo apt install -y libxml2-dev
                      sudo docker-php-ext-configure soap && sudo docker-php-ext-install soap

                      php -v

            # Download and cache dependencies
            - restore_cache:
                  keys:
                      # "composer.lock" can be used if it is committed to the repo
                      - v1-dependencies-{{ checksum "composer.lock" }}

            - run: composer install -n --prefer-dist

            - restore_cache:
                  keys:
                      - node-v1-{{ checksum "package.json" }}
                      - node-v1-
            - run: yarn install
            - save_cache:
                  key: node-v1-{{ checksum "package.json" }}
                  paths:
                      - node_modules

            - save_cache:
                  key: v1-dependencies-{{ checksum "composer.lock" }}
                  paths:
                      - ./vendor
                      - ./bin/.phpunit

            - persist_to_workspace:
                root: .
                paths: ./*

    unit_tests:
        <<: *default_executor
        steps:
            - attach_workspace:
                at: .
            - blackfire/setup
            - run:
                name: Blackfire tests
                environment:
                    APP_DEBUG: 0
                command: php bin/phpunit --group=blackfire

            - save_cache:
                key: v1-dependencies-{{ checksum "composer.lock" }}
                paths:
                    - ./vendor
                    - ./bin/.phpunit

    blackfire_build:
        <<: *default_executor
        steps:
            - blackfire/setup
            - blackfire-agent/build-trigger:
                endpoint: "https://hm2shukufy-a5i4gffd76b7w.eu.s5y.io/"
                environment: e97cbe91-24b0-40ed-8cb6-f3c9886bccc7

    blackfire_player:
        <<: *default_executor
        steps:
            - attach_workspace:
                at: .
            - *apcu_install
            - blackfire/setup
            - symfony/install
            - symfony/local_server_run
            - blackfire-player/run-scenario:
                scenario: scenario.bkf
                environment-name: Playground
                endpoint: "http://localhost:8000"
                variables: "variable_name1=value1,variable_name2=value2,foo=bar"

    symfony_deploy:
        <<: *default_executor
        steps:
            - attach_workspace:
                at: .
            - symfony/install
            - symfony/deploy:
                  project-id: a5i4gffd76b7w

workflows:
    version: 2
    build-and-tests:
        jobs:
            - build
            - unit_tests:
                requires:
                    - build
            - blackfire_player:
                requires:
                    - build
            - symfony_deploy:
                  requires:
                      - unit_tests
                      - blackfire_player
            - blackfire_build:
                  requires:
                      - symfony_deploy
