version: 2

jobs:
    build:
        docker:
            - image: circleci/php:7.3-node

        steps:
            - checkout

            - run:
                name: Install Blackfire
                command: |
                    wget -q -O - https://packages.blackfire.io/gpg.key | sudo apt-key add -
                    echo "deb http://packages.blackfire.io/debian any main" | sudo tee /etc/apt/sources.list.d/blackfire.list
                    sudo apt update
                    sudo apt-get install blackfire-agent blackfire-php
                    sudo sed -i -e "s/server-id=/server-id=${BLACKFIRE_SERVER_ID}/g" /etc/blackfire/agent
                    sudo sed -i -e "s/server-token=/server-token=${BLACKFIRE_SERVER_TOKEN}/g" /etc/blackfire/agent
                    sudo /etc/init.d/blackfire-agent restart
                    blackfire config --dump > ${HOME}/.blackfire.ini
                    sed -i -e "s/client-token=/client-id=${BLACKFIRE_CLIENT_ID}/g" ${HOME}/.blackfire.ini
                    sed -i -e "s/client-token=/client-token=${BLACKFIRE_CLIENT_TOKEN}/g" ${HOME}/.blackfire.ini
                    php -v

            # Download and cache dependencies
            - restore_cache:
                  keys:
                      # "composer.lock" can be used if it is committed to the repo
                      - v1-dependencies-{{ checksum "composer.lock" }}-{{ checksum "./bin/.phpunit/.7.5" }}
                      # fallback to using the latest cache if no exact match is found
                      - v1-dependencies-

            - run: composer install -n --prefer-dist

            - restore_cache:
                  keys:
                      - node-v1-{{ checksum "package.json" }}
                      - node-v1-
            - run: yarn install
            - save_cache:
                  key: node-v1-{{ checksum "package.json" }}
                  paths:
                      - node_modules

            - run:
                name: Blackfire tests
                environment:
                    APP_DEBUG: 0
                command: php bin/phpunit --group=blackfire

            - save_cache:
                  key: v1-dependencies-{{ checksum "composer.lock" }}-{{ checksum "./bin/.phpunit/.7.5" }}
                  paths:
                      - ./vendor
                      - ./bin/.phpunit
