version: 2.1
description: Foo

orbs:
    blackfire: blackfireio/php@dev:0.1

jobs:
    build:
        docker:
            - image: circleci/php:7.3-node

        steps:
            - checkout

            - blackfire/setup:
                  server_id: BLACKFIRE_SERVER_ID
                  server_token: BLACKFIRE_SERVER_TOKEN
                  client_id: BLACKFIRE_CLIENT_ID
                  client_token: BLACKFIRE_CLIENT_TOKEN

            # Download and cache dependencies
            - restore_cache:
                  keys:
                      # "composer.lock" can be used if it is committed to the repo
                      - v1-dependencies-{{ checksum "composer.lock" }}
                      # fallback to using the latest cache if no exact match is found
                      - v1-dependencies-

            - run: composer install -n --prefer-dist

            - restore_cache:
                  keys:
                      - node-v1-{{ checksum "package.json" }}
                      - node-v1-
            - run: yarn install
            - save_cache:
                  key: node-v1-{{ checksum "package.json" }}
                  paths:
                      - node_modules

            - run:
                name: Blackfire tests
                environment:
                    APP_DEBUG: 0
                command: php bin/phpunit --group=blackfire

            - save_cache:
                  key: v1-dependencies-{{ checksum "composer.lock" }}
                  paths:
                      - ./vendor
                      - ./bin/.phpunit
