version: 2.1
description: Foo

orbs:
    blackfire: blackfireio/php@dev:1.1
    blackfire-agent: blackfireio/agent@dev:1.2
    blackfire-player: blackfireio/player@dev:1.0

jobs:
    build:
        docker:
            - image: circleci/php:7.3-node

        steps:
            - checkout

            - run:
                  name: Install SOAP
                  command: |
                      sudo apt update && sudo apt install -y libxml2-dev
                      sudo docker-php-ext-configure soap
                      sudo docker-php-ext-install soap

            - blackfire/setup

            # Download and cache dependencies
            - restore_cache:
                  keys:
                      # "composer.lock" can be used if it is committed to the repo
                      - v1-dependencies-{{ checksum "composer.lock" }}
                      # fallback to using the latest cache if no exact match is found
                      - v1-dependencies-

            - run: composer install -n --prefer-dist

            - restore_cache:
                  keys:
                      - node-v1-{{ checksum "package.json" }}
                      - node-v1-
            - run: yarn install
            - save_cache:
                  key: node-v1-{{ checksum "package.json" }}
                  paths:
                      - node_modules

            - run:
                name: Blackfire tests
                environment:
                    APP_DEBUG: 0
                command: php bin/phpunit --group=blackfire

            - blackfire-agent/build-trigger:
                  endpoint: "https://gitlist.demo.blackfire.io/Twig/"
                  environment: Playground

            - save_cache:
                  key: v1-dependencies-{{ checksum "composer.lock" }}
                  paths:
                      - ./vendor
                      - ./bin/.phpunit

before_player: &before_player
    - run:
        name: Install & run Symfony server
        command: |
            wget https://get.symfony.com/cli/installer -O - | bash
            ~/.symfony/bin/symfony local:server:start -d

workflows:
    version: 2
    build_and_player:
        jobs:
            - build
            - blackfire-player/player-run:
                  scenario: scenario.bkf
                  environment-name: Playground
                  endpoint: "http://localhost:8000"
                  variables: "variable_name1=value1,variable_name2=value2,foo=bar"
                  before_run:
                      <<: *before_player
