version: 2.1
description: Foo

orbs:
    blackfire-php:
        commands:
            install-debian:
                parameters:
                    server_id:
                        type: env_var_name
                        default: BLACKFIRE_SERVER_ID
                    server_token:
                        type: env_var_name
                        default: BLACKFIRE_SERVER_TOKEN
                    client_id:
                        type: env_var_name
                        default: BLACKFIRE_CLIENT_ID
                    client_token:
                        type: env_var_name
                        default: BLACKFIRE_CLIENT_TOKEN
                steps:
                    - run:
                          name: Install Blackfire
                          command: |
                              wget -q -O - https://packages.blackfire.io/gpg.key | sudo apt-key add -
                              echo "deb http://packages.blackfire.io/debian any main" | sudo tee /etc/apt/sources.list.d/blackfire.list
                              sudo apt update
                              sudo apt-get install blackfire-agent blackfire-php
                              sudo sed -i -e "s/server-id=/server-id=<< parameters.server_id >>/g" /etc/blackfire/agent
                              sudo sed -i -e "s/server-token=/server-token=<< parameters.server_token >>/g" /etc/blackfire/agent
                              sudo /etc/init.d/blackfire-agent restart
                              blackfire config --dump > ${HOME}/.blackfire.ini.tmp && mv ${HOME}/.blackfire.ini.tmp ${HOME}/.blackfire.ini
                              sed -i -e "s/client-token=/client-id=<< parameters.client_id >>/g" ${HOME}/.blackfire.ini
                              sed -i -e "s/client-token=/client-token=<< parameters.client_token >>/g" ${HOME}/.blackfire.ini
                              php -v

jobs:
    build:
        docker:
            - image: circleci/php:7.3-node

        steps:
            - checkout

            - blackfire-php/install-debian

            # Download and cache dependencies
            - restore_cache:
                  keys:
                      # "composer.lock" can be used if it is committed to the repo
                      - v1-dependencies-{{ checksum "composer.lock" }}
                      # fallback to using the latest cache if no exact match is found
                      - v1-dependencies-

            - run: composer install -n --prefer-dist

            - restore_cache:
                  keys:
                      - node-v1-{{ checksum "package.json" }}
                      - node-v1-
            - run: yarn install
            - save_cache:
                  key: node-v1-{{ checksum "package.json" }}
                  paths:
                      - node_modules

            - run:
                name: Blackfire tests
                environment:
                    APP_DEBUG: 0
                command: php bin/phpunit --group=blackfire

            - save_cache:
                  key: v1-dependencies-{{ checksum "composer.lock" }}
                  paths:
                      - ./vendor
                      - ./bin/.phpunit
