version: 2.1
description: Foo

orbs:
    blackfire-php:
        commands:
            install-debian:
                parameters:
                    server_id:
                        type: env_var_name
                        default: BLACKFIRE_SERVER_ID
                    server_token:
                        type: env_var_name
                        default: BLACKFIRE_SERVER_TOKEN
                    client_id:
                        type: env_var_name
                        default: BLACKFIRE_CLIENT_ID
                    client_token:
                        type: env_var_name
                        default: BLACKFIRE_CLIENT_TOKEN
                steps:
                    - run:
                          name: Install Blackfire
                          command: |
                              wget -q -O - https://packages.blackfire.io/gpg.key | sudo apt-key add -
                              echo "deb http://packages.blackfire.io/debian any main" | sudo tee /etc/apt/sources.list.d/blackfire.list
                              sudo apt update
                              sudo apt-get install blackfire-agent blackfire-php
                              blackfire-agent -register --server-id=${<< parameters.server_id >>} --server-token=${<< parameters.server_token >>}
                              sudo /etc/init.d/blackfire-agent restart
                              blackfire config --client-id=${<< parameters.client_id >>} --client-token=${<< parameters.client_token >>}
jobs:
    build:
        docker:
            - image: circleci/php:7.3-node

        steps:
            - checkout

            - blackfire-php/install-debian:
                  server_id: BLACKFIRE_SERVER_ID
                  server_token: BLACKFIRE_SERVER_TOKEN
                  client_id: BLACKFIRE_CLIENT_ID
                  client_token: BLACKFIRE_CLIENT_TOKEN

            -   run:
                    name: Deactivate Xdebug
                    command: |
                        sudo sed -i -e "s/zend_extension=/;zend_extension=/g" /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
                        php -v

            # Download and cache dependencies
            - restore_cache:
                  keys:
                      # "composer.lock" can be used if it is committed to the repo
                      - v1-dependencies-{{ checksum "composer.lock" }}
                      # fallback to using the latest cache if no exact match is found
                      - v1-dependencies-

            - run: composer install -n --prefer-dist

            - restore_cache:
                  keys:
                      - node-v1-{{ checksum "package.json" }}
                      - node-v1-
            - run: yarn install
            - save_cache:
                  key: node-v1-{{ checksum "package.json" }}
                  paths:
                      - node_modules

            - run:
                name: Blackfire tests
                environment:
                    APP_DEBUG: 0
                command: php bin/phpunit --group=blackfire

            - save_cache:
                  key: v1-dependencies-{{ checksum "composer.lock" }}
                  paths:
                      - ./vendor
                      - ./bin/.phpunit
