version: 2.1
description: Foo

orbs:
    blackfire: blackfireio/php@dev:1.1
    blackfire-agent: blackfireio/agent@dev:1.2
    blackfire-player: blackfireio/player@dev:1.0

references:
    default_executor: &default_executor
        docker:
            - image: circleci/php:7.4-fpm-node

    symfony_server_start: &symfony_server_start
        run:
            name: "Install & run Symfony server"
            environment:
                APP_DEBUG: 0
            command: |
                wget https://get.symfony.com/cli/installer -O - | bash
                ~/.symfony/bin/symfony local:server:start -d

jobs:
    build:
        <<: *default_executor

        steps:
            - checkout

            - run:
                  name: Install SOAP
                  command: |
                      sudo apt update && sudo apt install -y libxml2-dev
                      sudo docker-php-ext-configure soap
                      sudo docker-php-ext-install soap

            # Download and cache dependencies
            - restore_cache:
                  keys:
                      # "composer.lock" can be used if it is committed to the repo
                      - v1-dependencies-{{ checksum "composer.lock" }}
                      # fallback to using the latest cache if no exact match is found
                      - v1-dependencies-

            - run: composer install -n --prefer-dist

            - restore_cache:
                  keys:
                      - node-v1-{{ checksum "package.json" }}
                      - node-v1-
            - run: yarn install
            - save_cache:
                  key: node-v1-{{ checksum "package.json" }}
                  paths:
                      - node_modules

            - save_cache:
                  key: v1-dependencies-{{ checksum "composer.lock" }}
                  paths:
                      - ./vendor
                      - ./bin/.phpunit

            - persist_to_workspace:
                root: .
                paths: ./*

    unit_tests:
        <<: *default_executor
        steps:
            - attach_workspace:
                at: .
            - blackfire/setup
            - run:
                name: Blackfire tests
                environment:
                    APP_DEBUG: 0
                command: php bin/phpunit --group=blackfire

            - save_cache:
                key: v1-dependencies-{{ checksum "composer.lock" }}
                paths:
                    - ./vendor
                    - ./bin/.phpunit

    blackfire_build:
        <<: *default_executor
        steps:
            - blackfire-agent/build-trigger:
                endpoint: "https://gitlist.demo.blackfire.io/Twig/"
                environment: Playground

    blackfire_player:
        <<: *default_executor
        steps:
            - attach_workspace:
                at: .
            - blackfire/setup
            - *symfony_server_start
            - blackfire-player/run-scenario:
                scenario: scenario.bkf
                environment-name: Playground
                endpoint: "http://localhost:8000"
                variables: "variable_name1=value1,variable_name2=value2,foo=bar"

workflows:
    version: 2
    build-and-tests:
        jobs:
            - build
            - unit_tests:
                requires:
                    - build
            - blackfire_build:
                requires:
                    - build
            - blackfire_player:
                requires:
                    - build
