name: My Workflow

on:
  push:
    branches: 
      - master
      - symfonyDeploy
  pull_request:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup PHP Action
      uses: shivammathur/setup-php@develop
      with:
        # Setup PHP version.
        php-version: '7.4'
        # Setup PHP extensions.
        extensions: blackfire, apcu, :xdebug
        # Add values to php.ini.
        #ini-values: # optional
        # Setup code coverage driver.
        #coverage: # optional
        # Setup popular tools globally.
        tools: blackfire, blackfire-player, symfony
      env:
        BLACKFIRE_SERVER_ID: ${{ secrets.BLACKFIRE_SERVER_ID }}
        BLACKFIRE_SERVER_TOKEN: ${{ secrets.BLACKFIRE_SERVER_TOKEN }}
        BLACKFIRE_CLIENT_ID: ${{ secrets.BLACKFIRE_CLIENT_ID }}
        BLACKFIRE_CLIENT_TOKEN: ${{ secrets.BLACKFIRE_CLIENT_TOKEN }}

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      if: steps.composer-cache.outputs.cache-hit != 'true'
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Blackfire versions
      run: |
        php -v
        blackfire version
        blackfire-agent -v

    - name: Blackfire config dump
      run: |
        php --ri blackfire
        sudo blackfire-agent -d

    - name: Profile list-users command
      env:
        APP_ENV: prod
        APP_DEBUG: 0
      run: blackfire run php bin/console app:list-users

    - name: Symfony local server start
      env:
        APP_ENV: prod
        APP_DEBUG: 0
      run: |
        symfony local:server:start -d
        php bin/console cache:warmup -e prod

    - name: Blackfire Player Action
      uses: ./github/actions/blackfire-player-run-action
      with:
        scenario-file: scenario.bkf
        endpoint: "http://localhost:8000"
        blackfire-env: Playground
      env:
        BLACKFIRE_SERVER_ID: ${{ secrets.BLACKFIRE_SERVER_ID }}
        BLACKFIRE_SERVER_TOKEN: ${{ secrets.BLACKFIRE_SERVER_TOKEN }}
        BLACKFIRE_CLIENT_ID: ${{ secrets.BLACKFIRE_CLIENT_ID }}
        BLACKFIRE_CLIENT_TOKEN: ${{ secrets.BLACKFIRE_CLIENT_TOKEN }}

#    - name: Blackfire Player
#      run: |
#        blackfire-player run --endpoint=http://localhost:8000 --blackfire-env=Playground scenario.bkf
